# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lcpa_cpp <- function(x, y, R_max = 3L, time_limit = 60L) {
    .Call(`_riskslimr_glpk_lcpa_cpp`, x, y, R_max, time_limit)
}

